# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Sat Jun 30 11:12:04 2018
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from wx import SplitterWindow
from wx import InfoBar
import wx.stc
from wx.stc import StyledTextCtrl
from PlotUtils import AnalysisPlotPanel
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1116, 590))
        self.window = SplitterWindow(self, wx.ID_ANY, style = wx.SP_LIVE_UPDATE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("ShulinPeng's ToolKit - Digital Signal Processing"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_3.Add(self.window, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyFrame

class ControlPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ControlPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.combo_box_script = wx.ComboBox(self, wx.ID_ANY, choices=[], style=0)
        self.button_run = wx.Button(self, wx.ID_ANY, _("Run"))
        self.text_ctrl_script = StyledTextCtrl(self, wx.ID_ANY)
        self.bar_info = InfoBar(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.OnSelectScript, self.combo_box_script)
        self.Bind(wx.EVT_BUTTON, self.OnRun, self.button_run)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ControlPanel.__set_properties
        self.button_run.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ControlPanel.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, _("Script:"))
        sizer_6.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add((5, 20), 0, 0, 0)
        sizer_6.Add(self.combo_box_script, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add((10, 20), 0, 0, 0)
        sizer_6.Add(self.button_run, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_7.Add((20, 10), 0, 0, 0)
        sizer_7.Add(self.text_ctrl_script, 1, wx.EXPAND, 0)
        sizer_7.Add(self.bar_info, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def OnSelectScript(self, event):  # wxGlade: ControlPanel.<event_handler>
        print("Event handler 'OnSelectScript' not implemented!")
        event.Skip()

    def OnRun(self, event):  # wxGlade: ControlPanel.<event_handler>
        print("Event handler 'OnRun' not implemented!")
        event.Skip()

# end of class ControlPanel

class PlotPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PlotPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.plotpanel = AnalysisPlotPanel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PlotPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PlotPanel.__do_layout
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(self.plotpanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_8)
        sizer_8.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PlotPanel
