#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade f172c83ff51d+ on Thu Apr  6 11:18:08 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from PlotUtils import AnalysisPlotPanel
from wx import InfoBar
import wx.stc
from wx.stc import StyledTextCtrl
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.combo_box_script = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.button_run = wx.Button(self, wx.ID_ANY, _("Run"))
        self.text_ctrl_script = StyledTextCtrl(self, wx.ID_ANY)
        self.bar_info = InfoBar(self, wx.ID_ANY)
        self.plotpanel = AnalysisPlotPanel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.OnSelectScript, self.combo_box_script)
        self.Bind(wx.EVT_BUTTON, self.OnRun, self.button_run)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("ShulinPeng's ToolKit - Digital Signal Processing"))
        self.SetSize((990, 679))
        self.button_run.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, _("Script:"))
        sizer_6.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add((5, 20), 0, 0, 0)
        sizer_6.Add(self.combo_box_script, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add((0, 0), 0, 0, 0)
        sizer_6.Add((10, 20), 0, 0, 0)
        sizer_6.Add(self.button_run, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_5.Add((20, 10), 0, 0, 0)
        sizer_5.Add(self.text_ctrl_script, 1, wx.EXPAND, 0)
        sizer_5.Add(self.bar_info, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_4.Add((10, 20), 0, 0, 0)
        sizer_4.Add(self.plotpanel, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        self.SetSize((990, 679))
        # end wxGlade

    def OnSelectScript(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnSelectScript' not implemented!")
        event.Skip()

    def OnRun(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnRun' not implemented!")
        event.Skip()

# end of class MyFrame
